### ISSUE TITLE
Base Flutter app setup

### ISSUE THREAD

**Issue by jainankit0811** [Techie-AI/Frontend#2]
- Initialized new Flutter project
- Added default Flutter app files
- Configured project settings and dependencies
- Verified initial build and run on emulator

**Comment by rohitagr0310** [comment]
Hi @jainankit0811 ,

Please update the Commit name and ensure it is concise and precise.

- [ ] Update the name of the Commit 
- [ ] Update the description of the Commit 

Thanks
